export const ProductData = [
  {
    id: 1,
    name: "Pizza Margherita",
    desc: "Pizza dough, mozzarella cheese, olive oil, garlic, fresh basil",
    price: 1999,
    image: "1.jpg",
    button: "Add to Cart",
  },
  {
    id: 2,
    name: "Hawaiian pizza",
    desc: "Pizza dough, tomato sauce, mozzarella cheese, cooked ham",
    price: 1999,
    image: "2.jpg",
    button: "Add to Cart",
  },
  {
    id: 3,
    name: "Pizza Ortolana",
    desc: "Pizza dough, artichoke hearts, red bell peppers, fresh mozzarella",
    price: 1999,
    image: "3.jpg",
    button: "Add to Cart",
  },
  {
    id: 4,
    name: "Eggs Florentine pizza",
    desc: "Bread flour, mozzarella, baby spinach, olive oil, milk",
    price: 1999,
    image: "4.jpg",
    button: "Add to Cart",
  },
  {
    id: 5,
    name: "Sourdough Pizza",
    desc: "Sourdough starter, red wheat flour, tipo 00, dough, olive oil",
    price: 1999,
    image: "5.jpg",
    button: "Add to Cart",
  },
  {
    id: 6,
    name: "Regina Pizza",
    desc: "Ham, mozzarella cheese, tomato, olive oil, flour",
    price: 1999,
    image: "6.jpg",
    button: "Add to Cart",
  },
];
